server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true

# 数据库连接配置
database:
  logger:
    path:    "logs/sql"
    level:   "all"
    stdout:  true
    ctxKeys: ["RequestId"]

  default:
    link:   "mysql:root:root@tcp(127.0.0.1:3306)/catbaby"
    debug:  true
# gf工具配置
gfcli:
  gen:
    dao:
      - link:     "mysql:root:root@tcp(127.0.0.1:3306)/catbaby"
        tables:   "user,post"
        jsonCase: "CamelLower"

