// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Comment is the golang structure of table comment for DAO operations like Where/Data.
type Comment struct {
	g.Meta    `orm:"table:comment, do:true"`
	Id        interface{} // 编号
	Pid       interface{} // 父级ID，为0表示顶级
	PostId    interface{} // 帖子ID
	UserId    interface{} // 评论人ID
	Status    interface{} // 评论状态 0表示屏蔽 1表示正常
	Content   interface{} // 评论内容
	CreatedAt *gtime.Time // 创建时间
	UpdatedAt *gtime.Time // 更新时间
}
