// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Post is the golang structure of table post for DAO operations like Where/Data.
type Post struct {
	g.Meta      `orm:"table:post, do:true"`
	Id          interface{} // 主键编号
	Title       interface{} // 标题
	Description interface{} // 文章描述
	UserId      interface{} // 作者编号
	CategoryId  interface{} // 分类编号
	Content     interface{} // 文章内容
	Status      interface{} // 文章状态:0禁用1正常
	CreatedAt   *gtime.Time // 创建时间
	UpdatedAt   *gtime.Time // 更新时间
}
