// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"threebody/internal/model"
)

type IRole interface {
	Create(ctx context.Context, in model.RoleCreateInput) error
	Update(ctx context.Context, in model.RoleUpdateInput) error
	List(ctx context.Context, in model.RoleListInput) (out *model.RoleListOutput, err error)
	Detail(ctx context.Context, in model.RoleDetailInput) (out *model.RoleDetailOutput, err error)
}

var localRole IRole

func Role() IRole {
	if localRole == nil {
		panic("implement not found for interface IRole, forgot register?")
	}
	return localRole
}

func RegisterRole(i IRole) {
	localRole = i
}
