// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"
	"github.com/gogf/gf/v2/frame/g"
	"threebody/internal/dao/internal"
	"threebody/internal/model/entity"
)

// internalUserDao is internal type for wrapping internal DAO implements.
type internalUserDao = *internal.UserDao

// userDao is the data access object for table user.
// You can define custom methods on it to extend its functionality as you wish.
type userDao struct {
	internalUserDao
}

var (
	// User is globally public accessible object for table user operations.
	User = userDao{
		internal.NewUserDao(),
	}
)

// Fill with you ideas below.

// FindOneByPhone 根据手机号查询一条记录
func (u *userDao) FindOneByPhone(ctx context.Context, phone string) (result *entity.User, err error) {
	err = u.Ctx(ctx).Where(g.Map{
		User.Columns().Phone: phone,
	}).Scan(&result)
	return
}

// Create 创建一条记录
func (u *userDao) Create(ctx context.Context, data interface{}) error {
	_, err := u.Ctx(ctx).Data(data).Insert()
	return err
}
