// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Comment is the golang structure for table comment.
type Comment struct {
	Id        uint64      `json:"id"        ` // 编号
	Pid       uint64      `json:"pid"       ` // 父级ID，为0表示顶级
	PostId    uint64      `json:"postId"    ` // 帖子ID
	UserId    uint64      `json:"userId"    ` // 评论人ID
	Status    uint        `json:"status"    ` // 评论状态 0表示屏蔽 1表示正常
	Content   string      `json:"content"   ` // 评论内容
	CreatedAt *gtime.Time `json:"createdAt" ` // 创建时间
	UpdatedAt *gtime.Time `json:"updatedAt" ` // 更新时间
}
