// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Post is the golang structure for table post.
type Post struct {
	Id          uint64      `json:"id"          ` // 主键编号
	Title       string      `json:"title"       ` // 标题
	Description string      `json:"description" ` // 文章描述
	UserId      uint64      `json:"userId"      ` // 作者编号
	CategoryId  uint64      `json:"categoryId"  ` // 分类编号
	Content     string      `json:"content"     ` // 文章内容
	Status      uint        `json:"status"      ` // 文章状态:0禁用1正常
	CreatedAt   *gtime.Time `json:"createdAt"   ` // 创建时间
	UpdatedAt   *gtime.Time `json:"updatedAt"   ` // 更新时间
}
