// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Role is the golang structure for table role.
type Role struct {
	Id            uint64      `json:"id"            ` // 主键编号
	Avatar        string      `json:"avatar"        ` // 头像
	Name          string      `json:"name"          ` // 名称
	Nickname      string      `json:"nickname"      ` // 别名
	SurvivalStage string      `json:"survivalStage" ` // 生存阶段
	Nationality   string      `json:"nationality"   ` // 国籍
	Achievement   string      `json:"achievement"   ` // 主要成就
	Gender        uint        `json:"gender"        ` // 是否展示:0女1男
	Content       string      `json:"content"       ` // 介绍
	IfShow        uint        `json:"ifShow"        ` // 是否展示:0否1是
	CreatedAt     *gtime.Time `json:"createdAt"     ` // 创建时间
	UpdatedAt     *gtime.Time `json:"updatedAt"     ` // 更新时间
}
