// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id        int64       `json:"id"        ` // 用户编号
	Avatar    string      `json:"avatar"    ` // 头像
	Nickname  string      `json:"nickname"  ` // 用户昵称
	Phone     string      `json:"phone"     ` // 手机号
	Password  string      `json:"password"  ` // 密码
	Status    uint        `json:"status"    ` // 状态:0禁用1正常
	CreatedAt *gtime.Time `json:"createdAt" ` // 创建时间
}
