GET http://127.0.0.1:8000/frontend/role/29
Accept: application/json


GET http://127.0.0.1:8000/frontend/role
Accept: application/json

{"size":2,"page":1,"search":"Bob"}

###
POST http://127.0.0.1:8000/backend/role
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTcyMjQ0MTAsImlkIjoxNCwibmlja25hbWUiOiJ6aGFuZ3NhbiIsIm9yaWdfaWF0IjoxNjU3MjA2NDEwLCJwaG9uZSI6IjE1MTA1MTkxMTgyIn0.YHVuIk51Ng0pde_wnhTIJEK1lFW-2Ath53iRYByPe2U

{
  "avatar": "https://goframe.org/pages/viewpage.action?pageId=1114517&src=contextnavpagetreemode",
  "name": "KangKang",
  "nickname": "康康",
  "survival_stage": "掩体",
  "nationality": "汉族",
  "achievement": "123",
  "gender": "1",
  "content": "string",
  "if_show": "1"
}

###


PUT http://127.0.0.1:8000/backend/role
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTY2ODU1ODUsImlkIjoyMywibmlja25hbWUiOiJ6aGFuZ3NhbiIsIm9yaWdfaWF0IjoxNjU2NjY3NTg1LCJwaG9uZSI6IjE1MTA1MTkxMTgyIn0.ZV3dd1hqvsPUR4CsU9E00w6u0KcLq1tBK9BfhFvLRiE

{
  "id": "1",
  "avatar": "https://goframe.org/pages/viewpage.action?pageId=30736904&focusedCommentId=51951498&refresh=1656668186708#comment-51951498",
  "name": "张三",
  "nickname": "string",
  "survival_stage": "string",
  "nationality": "string",
  "achievement": "string",
  "gender": "1",
  "content": "string",
  "if_show": "0"
}

